# Generated by Django 4.0.4 on 2023-03-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STUser',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
            ],
        ),
    ]
